#!/bin/sh

repository_name=${1}
sync_uri=${2}
repository_path=${3}

ret=0

if [ -n "${repository_name}" ]
then
	if [ "${repository_name}" != "gentoo" ]
	then
		if ! egencache --update --repo="${repository_name}" --jobs=4 --load-average=4
		then
			echo "error: egencache failed"
			ret=1
		fi
	fi
fi

exit "${ret}"
